# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-02-19 11:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20170219_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='subtypes',
            field=models.ManyToManyField(blank=True, to='booking.SubType'),
        ),
    ]
